// GENERE par scripts/extraire-suivi.mjs — ne pas modifier a la main.
// Les 342 RDV du fichier de suivi de juin : vendeur, site, source, resultat.
// Aucun nom de client, aucun vehicule.

export interface LigneSuiviSource {
  vendeur: string;
  site: string;
  /// « Relance », « Showroom », ou vide quand la case n'a pas ete remplie.
  source: string;
  /// Le texte ecrit dans la case resultat, tel quel. Vide = a traiter.
  resultat: string;
}

export const SUIVI_JUIN: LigneSuiviSource[] = [
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"STOCK"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"STOCK"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"OFFRE EN COURS"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"OFFRE EN COURS"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"VALENTIN PARPINELLI","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+CS"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"SÈCHE"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"THIERRY DUBERNAT","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"STOCK"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"STOCK+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"OCEANE ESPINASSE","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"STOCK"},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"SÈCHE"},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"OFFRE EN COURS"},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"BLANDINE CLÉMENT","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"OFFRE EN COURS"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"SÈCHE"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"SÈCHE"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"SÈCHE"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Showroom","resultat":""},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+CS"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"SÈCHE"},
  {"vendeur":"THOMAS SOULIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":"SÈCHE"},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"SÈCHE"},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"CHRISTOPHE BROSSEAU","site":"CLERMONT-FERRAND","source":"Relance","resultat":"SÈCHE"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":"STOCK"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"CS"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"THÉO ROUSSET","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"SÈCHE"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"SÈCHE"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"CS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"STOCK"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"QUENTIN BELLAIGUES","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"SÈCHE"},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"JEAN-PIERRE FERRIER","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"STOCK"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"SÈCHE"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"STOCK"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Showroom","resultat":"STOCK+CS"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"JULIEN BIASUTTI","site":"CLERMONT-FERRAND","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"PIERRE-EDOUARD LAROCHE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"PIERRE-EDOUARD LAROCHE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"PIERRE-EDOUARD LAROCHE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"PIERRE-EDOUARD LAROCHE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"PIERRE-EDOUARD LAROCHE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"PIERRE-EDOUARD LAROCHE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"PIERRE-EDOUARD LAROCHE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"PIERRE-EDOUARD LAROCHE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"PIERRE-EDOUARD LAROCHE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"PIERRE-EDOUARD LAROCHE","site":"CLERMONT-FERRAND","source":"Relance","resultat":""},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"DIAC"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"DIAC"},
  {"vendeur":"ANTHONY DONAS","site":"MOZAC","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":"DIAC"},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":"DIAC"},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"JORDAN CALDEIRA","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN RABOISSON","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"KEVIN DIJOUX","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"UGO FERVEL","site":"MOZAC","source":"Relance","resultat":""},
  {"vendeur":"ROBIN GUERY","site":"USSEL","source":"Showroom","resultat":"OFFRE EN COURS"},
  {"vendeur":"ROBIN GUERY","site":"USSEL","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"ROBIN GUERY","site":"USSEL","source":"Relance","resultat":""},
  {"vendeur":"ROBIN GUERY","site":"USSEL","source":"Relance","resultat":""},
  {"vendeur":"ROBIN GUERY","site":"USSEL","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"ROBIN GUERY","site":"USSEL","source":"Relance","resultat":""},
  {"vendeur":"ROBIN GUERY","site":"USSEL","source":"Relance","resultat":""},
  {"vendeur":"ROBIN GUERY","site":"USSEL","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"JULIEN SPADAT","site":"USSEL","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"JULIEN SPADAT","site":"USSEL","source":"Showroom","resultat":"DIAC+CS"},
  {"vendeur":"JULIEN SPADAT","site":"USSEL","source":"Relance","resultat":""},
  {"vendeur":"JULIEN SPADAT","site":"USSEL","source":"Relance","resultat":""},
  {"vendeur":"JULIEN SPADAT","site":"USSEL","source":"Relance","resultat":""},
  {"vendeur":"JULIEN SPADAT","site":"USSEL","source":"Relance","resultat":""},
  {"vendeur":"JULIEN SPADAT","site":"USSEL","source":"Relance","resultat":""},
  {"vendeur":"JULIEN SPADAT","site":"USSEL","source":"Showroom","resultat":"DIAC+STOCK"},
  {"vendeur":"JULIEN SPADAT","site":"USSEL","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"JULIEN SPADAT","site":"USSEL","source":"Relance","resultat":""},
  {"vendeur":"JULIEN SPADAT","site":"USSEL","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Showroom","resultat":"OFFRE EN COURS"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Relance","resultat":"RDV ANNULÉ"},
  {"vendeur":"QUENTIN VANINI","site":"MASSAGETTES","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Relance","resultat":"DIAC+CS"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Relance","resultat":"SÈCHE"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Showroom","resultat":"OFFRE EN COURS"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Showroom","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Relance","resultat":"CLOS SANS SUITE"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Relance","resultat":"OFFRE EN COURS"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Relance","resultat":"DIAC+STOCK+CS"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Showroom","resultat":"OFFRE EN COURS"},
  {"vendeur":"VIRGINIE CUMINAL","site":"MASSAGETTES","source":"Relance","resultat":"CLOS SANS SUITE"},
];
